add_perturbation: false
all_atoms: true
atom_max_neighbors: 8
atom_radius: 5
balance: false
batch_size: 8
batch_size_preprocessing: 1
best_model_save_frequency: 10
c_alpha_max_neighbors: 24
cache_creation_id: 1
cache_ids_to_combine:
- '1'
cache_path: data/cache_confidence
chain_cutoff: 10
ckpt: best_model.pt
confidence_dropout: 0.0
confidence_no_batchnorm: false
config: null
cross_distance_embed_dim: 32
cross_max_distance: 80
data_dir: data/waterbind
distance_embed_dim: 32
dropout: 0.1
dynamic_max_cross: true
embedding_scale: 10000
embedding_type: sinusoidal
esm_embeddings_path: data/confidence_esm2_embeddings.pt
inference_steps: 20
limit_complexes: 0
log_dir: workdir
lr: 0.001
main_metric: confidence_loss
main_metric_goal: min
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
model_save_frequency: 0
multiplicity: 1
n_epochs: 50
no_batch_norm: false
no_torsion: false
ns: 24
num_conformers: 1
num_conv_layers: 3
num_workers: 1
nv: 6
original_model_dir: workdir/all_atoms_score_model_res15_17092_02_dgx04
original_pdb_dir: workdir
project: diffwater_confidence
receptor_radius: 15.0
remove_hs: true
restart_dir: null
rmsd_classification_cutoff: 1.0
rmsd_prediction: true
run_name: confidence_model_17092_03_sigmoid_rr15
running_mode: train
samples_per_complex: 1
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 50
sigma_embed_dim: 32
split_test: data/splits/test_res15.txt
split_train: data/splits/train_res15.txt
split_val: data/splits/val_res15.txt
transfer_weights: false
use_original_model_cache: false
use_second_order_repr: false
w_decay: 0.0
wandb: true
