name: superwater
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - alsa-lib=1.2.8
  - anyio=4.7.0
  - aom=3.5.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attr=2.5.1
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - biopandas=0.5.1
  - biopython=1.84
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - ffmpeg=4.3
  - fftw=3.3.10
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gstreamer-orc=0.4.40
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=8.3.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.31.0
  - isoduration=20.11.0
  - jack=1.9.22
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.11.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kernel-headers_linux-64=3.10.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.11.1.6
  - libcups=2.3.3
  - libcurand=10.3.7.77
  - libcurl=7.88.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdb=6.2.32
  - libdeflate=1.14
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.6.4
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=14.2.0
  - libgcrypt=1.11.0
  - libgcrypt-devel=1.11.0
  - libgcrypt-lib=1.11.0
  - libgcrypt-tools=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnghttp2=1.52.0
  - libnpp=11.8.0.86
  - libnsl=2.0.0
  - libnvjpeg=11.9.0.86
  - libogg=1.3.5
  - libopenblas=0.3.28
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=12.20
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.10.0
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=252
  - libtasn1=4.19.0
  - libtiff=4.4.0
  - libtool=2.4.7
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - looseversion=1.3.0
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mmtf-python=1.1.3
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpg123=1.32.9
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - mysql=5.7.24
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbclient=0.10.2
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.2.1
  - notebook-shim=0.2.4
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.10.1
  - numpy=2.1.3
  - numpy-base=2.1.3
  - openbabel=3.1.1
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openldap=2.6.4
  - openssl=3.4.0
  - overrides=7.7.0
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.2
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - ply=3.11
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.0
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.2
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - send2trash=1.8.3
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.3
  - svt-av1=1.4.1
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - click==8.1.8
      - deepspeed==0.5.9
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - e3nn==0.5.4
      - einops==0.8.0
      - fair-esm==2.0.0
      - frozenlist==1.5.0
      - fsspec==2023.3.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - hjson==3.1.0
      - lightning-utilities==0.11.9
      - ml-collections==1.0.0
      - multidict==6.1.0
      - ninja==1.11.1.3
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - propcache==0.2.1
      - protobuf==5.29.2
      - py-cpuinfo==9.0.0
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pytorch-lightning==2.5.0.post0
      - rdkit==2024.3.6
      - rustworkx==0.15.1
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - smmap==5.0.1
      - spyrmsd==0.8.0
      - sympy==1.13.1
      - torch-cluster==1.6.3+pt25cu118
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt25cu118
      - torch-sparse==0.6.18+pt25cu118
      - torch-spline-conv==1.2.2+pt25cu118
      - torchmetrics==1.6.0
      - wandb==0.19.1
      - yarl==1.18.3
