all_atoms: true
atom_max_neighbors: 8
atom_radius: 5
batch_size: 8
c_alpha_max_neighbors: 24
cache_path: data/cache
config: null
cross_distance_embed_dim: 64
cross_max_distance: 80
cudnn_benchmark: true
data_dir: data/waterbind
distance_embed_dim: 64
dropout: 0.1
dynamic_max_cross: true
ema_rate: 0.999
embedding_scale: 1000
embedding_type: sinusoidal
esm_embeddings_path: data/dataset_waterbind_embeddings_output
inference_earlystop_goal: max
inference_earlystop_metric: valinf_rmsds_lt2
inference_steps: 20
limit_complexes: 0
log_dir: workdir
lr: 0.001
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
n_epochs: 300
no_batch_norm: false
ns: 24
num_conformers: 1
num_conv_layers: 3
num_dataloader_workers: 10
num_inference_complexes: 100
num_workers: 10
nv: 6
pin_memory: false
project: difwater_train
receptor_radius: 15.0
remove_hs: true
restart_dir: null
restart_lr: null
run_name: all_atoms_score_model_res15_17092_02_dgx04
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 30
sigma_embed_dim: 64
split_test: data/splits/test_res15.txt
split_train: data/splits/train_res15.txt
split_val: data/splits/val_res15.txt
test_sigma_intervals: true
tr_sigma_max: 30.0
tr_sigma_min: 0.1
tr_weight: 1
train_inference_freq: null
use_ema: true
use_second_order_repr: false
val_inference_freq: null
w_decay: 0.0
wandb: true
